# Generated by Django 5.0.7 on 2024-07-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_currencytype_balance_currency_type_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currency',
            new_name='Sum',
        ),
    ]
