# Generated by Django 5.0.7 on 2024-07-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_currency_sum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sum',
            new_name='Currency',
        ),
    ]
