# Generated by Django 5.0.7 on 2024-07-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_sum_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
