# Generated by Django 5.0.7 on 2024-07-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_balance_amount_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
