# Generated by Django 5.0.7 on 2024-07-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_balance_amount_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
